kind: pipeline
type: docker
name: default

steps:
- name: ssh
  image: appleboy/drone-ssh
  settings:
    host: 35.221.234.248
    username:
      from_secret: username
    key:
      from_secret: ssh_key
    port: 22
    script:
      - echo hello
      - echo world
      - cd Projects/Drone/
      - git pull
    when:
      branch:
      - main