kind: pipeline
type: docker
name: default

steps:
- name: ssh
  image: appleboy/drone-ssh
  when:
    branch:
    - main
  settings:
    host: 35.221.234.248
    username:
      from_secret: username
    key:
      from_secret: ssh_key
    port: 22
    script:
      - echo hello
      - echo world
      - cd Projects/Drone/
      - git pull
- name: dev_action                     # 事件三：可自行定義的名稱
  image: plugins/git                   # 使用 plugins/git  容器
  commands:                            # 預執行的 shell 指令，這邊印出 111111 內容
    - echo "111111"
  when:                                # 當觸發條件為 develop 分支時會執行的動作
    branch:
    - test-branch