kind: pipeline
type: ssh
name: default

server:
  host: 35.221.234.248
  user:
    from_secret: username
  password:
    from_secret: password
  port: 22

steps:
- name: pull
  commands:
  - cd Projects/Drone/
  - git pull